### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Erz-spec** [1104mc/staffstuff#10]
Amikor ráraktam magamra a timeoutot akkor nincsen olyan parancs amivel le is tudnám venni magamról. Szerintem hasznos lenne egy ilyen parancs.

**Comment by ProgrammerPeter2** [comment]
Listáznád is az aktív némításokat? @Erz-spec

**Comment by Erz-spec** [comment]
Igen az is egy hasznos dolog lenne, persze csak ha van kedved megcsinálni.

**Comment by Erz-spec** [comment]
Miben tudok ezzel kapcsolatban segíteni?

**Comment by ProgrammerPeter2** [comment]
Szóval, a fejlesztések:

- [ ] A `tmPlayers` listát a `commands.TimeoutCommand` parancsból a `model.TimeoutedPlayer` osztályba kell mozgatni
- [ ] A `model.TimeoutedPlayer` osztály új függvénye: `toMessage()`, melynek kimenete egy Component a java edition számára. Tartalmazza a némított játékos nevét és a némítás hátralevő idejét.
... and more
