### ISSUE TITLE
Kick parancs ötlet/issue

### ISSUE THREAD

**Issue by Erz-spec** [1104mc/staffstuff#12]
Amikor kickelem magamat akkor angolul hozza fel azt, hogy ki lettem kickelve. Nekem nem baj, de lehet valaki nem értené, hogy mi van, ha kapja a kicket. Illetve lehet jól jönne egy indok is a kickhez, hogy pl. kirúgom lőrincet vagy most ez igazából lehet bárki, de lehessen indokot odaírni pl. trollkodás.

**Comment by ProgrammerPeter2** [comment]
Ha nem adsz meg üzenetet, akkor az alap kick plugin a kliensed nyelvén írja meg neked, hogy ki lettél rúgva.

**Comment by ProgrammerPeter2** [comment]
![Screenshot_20230728-164618_Minecraft](https://github.com/1104mc/staffstuff/assets/66070387/176e10b1-5ecd-427b-840c-c40dd31654cb)
