### ISSUE TITLE
Fordítások

### ISSUE THREAD

**Issue by Erz-spec** [1104mc/staffstuff#9]
Amikor a commandokat aktiválni akarom pl. a /spectate parancsot akkor a többi szöveget angolul kapom meg ami nekem nem igazán probléma, de ha esetleg téged zavarna Peti akkor segíthetek az átfordításban. A probléma ugyanúgy fennáll a Timeout commandnál is de ott ha valakire rárakom a timeoutot akkor kijelzi, hogy sikeresen ráraktam xx nevű emberre a to-t. És ezt magyarul ugye. A  többi mind fordítatlan.
Ui. Szinte minden angolul van a parancsok közül kivéve a timeout amikor kiosztod.

**Comment by ProgrammerPeter2** [comment]
Alapvetően úgy gondolom, hogy akik használnák a staff parancsokat, azok értenek angolul, ahol pedig a program másokkal is kommunikál, ott szerintem lefordítottam amit kell.

**Comment by Erz-spec** [comment]
Rendben, értem.

**Comment by Erz-spec** [comment]
Mit kéne lefordítani? Vagy hogyan tudom ezt megcsinálni?
